# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import os
import shutil
from openpyxl import load_workbook
from PyQt5.QtWidgets import QApplication,QMainWindow
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 26, 481, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(lambda:self.function1(MainWindow))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "日期"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label_2.setText(_translate("MainWindow", "选择"))
        self.radioButton.setText(_translate("MainWindow", "平差、未平差"))
        self.label.setText(_translate("MainWindow", "选择"))
        self.pushButton.setText(_translate("MainWindow", "点击运行"))
        self.menu.setTitle(_translate("MainWindow", "生成主体沉降原始文件"))
    def function1(self,MainWindow):
        path1 = "D:\\2021\\基坑监测\\2019巷口\\原始数据3\\"  # 目标文件路径
        path3 = "D:\\2021\\基坑监测\\2019巷口\\原始数据1\\"  # 源文件路径同上
        dateset_path = "D:\\2021\\基坑监测\\2019巷口\\数据库.xlsx"

        workbook = load_workbook(dateset_path)
        sheet1 = workbook.get_sheet_by_name("日报")
        for zz in range(2, sheet1.max_row + 1):
            if ((sheet1.cell(zz, 2).value is None) or (sheet1.cell(zz, 2).value == '')):  # 根据判断是否为无参数None或者空来判断行数
                row2 = zz - 1
                break
            else:
                row2 = sheet1.max_row  # 根据日报获取期数
        file_names = os.listdir(path3)
        print(len(file_names))
        print("+++++++++++++++++++++")
        qua_path = "D:\\2021\\基坑监测\\2018巷口\\质量评定.doc"
        for j in range(2, row2 + 1):
            date1 = sheet1.cell(j, 2).value
            date3 = "第" + str(j - 1) + "期" + str(date1)
            x1 = date3.replace('-', '年', 1)
            x2 = x1.replace('-', '月', 1)
            x3 = x2.replace(' 00:00:00', '日', 1)  # 通过将日期datetime格式转换成字符串的形式将对应的2018/9/20 00：00：00转换成汉字2018年9月20日
            datex2 = path1 + x3
            os.makedirs(datex2)
            datex3 = datex2 + '\\' + '原始数据'
            os.makedirs(datex2 + '\\' + '原始数据')
            os.makedirs(datex2 + '\\' + '中间报告')
            for name in file_names:
                path4 = path3 + '\\' + name
                B1 = name[-3:]
                if (name[-3:] == 'dat'):
                    y2 = name.index('测')  ########根据名称的最后一个字来进行遍历
                    y3 = name.index('.')
                    if (str(j - 1) == name[y2 + 1:y3]):
                        shutil.copy(path4, datex3)  # 将通过遍历源目标文件下的dat文件拷贝到对应的目标文件夹下
                        shutil.copy(qua_path, datex2)
if __name__ == '__main__':
    app=QApplication(sys.argv)
    MainWindow=QMainWindow()
    ui=Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

